INFO - Log file for this run: /home/ilena7440/LSQ/out/MobileNetv2_cifar10_a8w8_5_20221102-132324/MobileNetv2_cifar10_a8w8_5_20221102-132324.log
INFO - TensorBoard data directory: /home/ilena7440/LSQ/out/MobileNetv2_cifar10_a8w8_5_20221102-132324/tb_runs
Files already downloaded and verified
Files already downloaded and verified
INFO - Dataset `cifar10` size:
          Training Set = 50000 (391)
        Validation Set = 10000 (79)
              Test Set = 10000 (79)
hello
********************pre-trained*****************
Traceback (most recent call last):
  File "main.py", line 144, in <module>
    main()
  File "main.py", line 67, in main
    model = create_model(args)
  File "/home/ilena7440/LSQ/model/model.py", line 37, in create_model
    model = mobilenetv2_cifar10(pretrained = args.pre_trained)
  File "/home/ilena7440/LSQ/model/mobilenet_cifar10.py", line 185, in mobilenetv2_cifar10
    return _mobilenetv2('mobilenetv2', 1.0, pretrained, num_classes = 10)
  File "/home/ilena7440/LSQ/model/mobilenet_cifar10.py", line 174, in _mobilenetv2
    print(state_dict.key())
AttributeError: 'dict' object has no attribute 'key'